syntax = "proto3";

package proto.gradido;

import "gradido_transaction.proto";
import "basic_types.proto";
import "ledger_metadata.proto";

/*
	id will be set by Node server
	running_hash will be also set by Node server,
	  calculated from previous transaction running_hash and this id, transaction and received;
*/

message ConfirmedTransaction {
    uint64 id = 1;
    GradidoTransaction transaction = 2;
    Timestamp confirmed_at = 3;
    uint32 version_number = 4;
    bytes running_hash = 5;
    LedgerAnchor ledger_anchor  = 6; // message id in underlying blockchain like iota

    repeated AccountBalance account_balances = 7;
    BalanceDerivation balance_derivation = 8;
}
