syntax = "proto3";

package proto.gradido;
import "proto/hiero/basic_types.proto"; 

message LedgerAnchor {
  enum AnchorType {
    ANCHOR_UNSPECIFIED = 0;
    IOTA_MESSAGE = 1;
    HIERO_TRANSACTION = 2;
    LEGACY_GRADIDO_DB = 3; // archived, non-deterministic
  }

  AnchorType type = 1;

  oneof anchor_id {
    bytes iota_message_id = 2;
    hiero.TransactionID hiero_transaction_id = 3;
    uint64 legacy_transaction_id = 4;
  }
}

enum BalanceDerivation {
  DERIVATION_UNSPECIFIED = 0;
  // Balances & decay can be recalculated deterministically
  DERIVATION_NODE_COMPUTED = 1;
  // Balances are accepted as-is from external / legacy system
  DERIVATION_EXTERNAL_AUTHORITATIVE = 2;
};