syntax = "proto3";

package proto.gradido;
import "hiero_basic_types.proto";

message LedgerAnchor {
  enum Type {
    UNSPECIFIED = 0;
    IOTA_MESSAGE_ID = 1;
    HIERO_TRANSACTION_ID = 2;
    LEGACY_GRADIDO_DB_TRANSACTION_ID = 3; // archived, non-deterministic
    NODE_TRIGGER_TRANSACTION_ID = 4; // for by gradido node triggered transactions
    LEGACY_GRADIDO_DB_COMMUNITY_ID = 5;
    LEGACY_GRADIDO_DB_USER_ID = 6;
    LEGACY_GRADIDO_DB_CONTRIBUTION_ID = 7;
    LEGACY_GRADIDO_DB_TRANSACTION_LINK_ID = 8;
  }

  Type type = 1;

  oneof anchor_id {
    bytes iota_message_id = 2;
    TransactionID hiero_transaction_id = 3;
    uint64 legacy_transaction_id = 4;
    uint64 node_trigger_transaction_id = 5;
    uint64 legacy_community_id = 6;
    uint64 legacy_user_id = 7;
    uint64 legacy_contribution_id = 8;
    uint64 legacy_transaction_link_id = 9;
  }
}

enum BalanceDerivation {
  UNSPECIFIED = 0;
  // Balances & decay can be recalculated deterministically
  NODE = 1;
  // Balances are accepted as-is from external / legacy system
  EXTERN = 2;
};
