/**
 * # Basic Types
 * Fundamental message types used across transactions and state as field types.
 *
 * ### Requirements for identifier values
 * - Most entities in the network SHALL be identified by a multi-part
 *   identifier. These identifier values SHALL consist of a shard, a realm, and
 *   an entity identifier.
 * - Shard, Realm, and Entity Number MUST all be whole numbers.
 * - A Shard SHALL be globally unique.
 * - A Realm MAY be reused between shards, but SHALL be unique within a shard.
 * - An Entity Number MAY be reused between shards and realms, but SHALL be
 *   unique within each combination of shard and realm.
 * - Every object (e.g. account, file, token, etc...) SHALL be scoped to exactly
 *   one realm and shard. Thus a File has a FileID, a numeric triplet, such as
 *   0.0.2 for shard 0, realm 0, entity 2.
 * - Identifier values SHOULD use an Entity Number as the third component of the
 *   identifier. Some, however, MAY use alternative or composite values for the
 *   Entity portion of the three part identifier. Any such alternative or
 *   composite value MUST be unique within that shard and realm combination.
 * - The entity portion of the identifier, regardless of type, MUST be unique
 *   within that realm and shard combination and MAY be globally unique.
 * - The triplet of shard.realm.entity MUST be globally unique, even across
 *   different identifier types.
 * - Each realm SHALL maintain a single counter for entity numbers, so if there
 *   is an identifier with value 0.1.2, then there MUST NOT be an identifier
 *   with value 0.1.2 for any other object.
 *
 * ### Keywords
 * The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
 * "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
 * document are to be interpreted as described in
 * [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
 * [RFC8174](https://www.ietf.org/rfc/rfc8174).
 */
syntax = "proto3";

package proto.hiero;

import "proto/gradido/basic_types.proto";

/**
 * A unique identifier for an Hedera account.
 *
 * An account identifier is of the form `shard.realm.[number|alias]`.<br/>
 * The identifier MAY use the alias form when transferring HBAR to a public key
 * before the account for that key is created, when only the alias value is
 * known, or in some smart contracts that use the EVM address style alias to
 * refer to Accounts.<br/>
 * When the account entry is completed, the alias SHALL be stored separately in
 * the Account record, and the identifier in the Account SHALL use the
 * `accountNum` form.
 *
 * ---
 * ### Additional Notes
 *
 * #### Alias
 * There is considerable complexity with `alias` (aka `evm_address`) for
 * Accounts. Much of this comes from the existence of a "hidden" alias for
 * almost all accounts, and the reuse of the alias field for both EVM reference
 * and "automatic" account creation.<br/>
 * For the purposes of this specification, we will use the following terms for
 * clarity.
 *   - `key_alias`<br/>
 *      The account public key as a protobuf serialized message and used for
 *      auto-creation and subsequent lookup. This is only valid if the account
 *      key is a single `primitive` key, either Ed25519 or ECDSA_SECP256K1.
 *   - `evm_address`<br/>
 *     Exists for every account and is one of
 *      - `contract_address`<br/>
 *        The 20 byte EVM address prescribed by `CREATE` or `CREATE2`
 *      - `evm_key_address`<br/>
 *        An arbitrary 20 byte EVM address that, for a usable externally owned
 *        account (EOA) SHALL be the rightmost 20 bytes of the Keccak-256 hash
 *        of a ECDSA_SECP256K1 key.<br/>
 *        Such accounts may be created in one of three ways:
 *        - Sending hbar or fungible tokens to an unused
 *          ECDSA_SECP256K1 key alias.
 *        - Sending hbar or fungible tokens to an unassigned 20-byte
 *          EVM address.
 *        - Submitting a `CryptoCreate` signed with the corresponding
 *          private key.
 *      - `long_zero`<br/>
 *        A synthetic 20 byte address inferred for "normally" created accounts.
 *        It is constructed from the "standard" AccountID as follows.
 *         1. 4 byte big-endian shard number
 *         1. 8 byte big-endian realm number
 *         1. 8 byte big-endian entity number<br/>
 *
 * The `alias` field in the `Account` message SHALL contain one of four values
 * for any given account.
 *   - The `key_alias`, if the account was created by transferring HBAR to the
 *     `key_alias` public key value.
 *   - The `evm_key_address` if the account was created from an EVM public key
 *   - The `contract_address` if the account belongs to an EVM contract
 *   - Not-Set/null/Bytes.EMPTY (collectively `null`) if the account was
 *     created normally
 *
 * If the `alias` field of an `Account` is any form of `null`, then the account
 * MAY be referred to by `alias` in an `AccountID` by using the `long_zero`
 * address for the account.<br/>
 * This "hidden default" alias SHALL NOT be stored, but is synthesized by the
 * node software as needed, and may be synthesized by an EVM contract or client
 * software as well.
 *
 * ---
 *
 * #### Alias forms
 * An `AccountID` in a transaction MAY reference an `Account` with
 * `shard.realm.alias`.<br/>
 * If the account `alias` field is set for an Account, that value SHALL be the
 * account alias.<br/>
 * If the account `alias` field is not set for an Account, the `long_zero` alias
 * SHALL be the account alias.
 */
message AccountID {
    /**
     * A whole number shard identifier.
     */
    int64 shardNum = 1;

    /**
     * A whole number realm identifier.
     */
    int64 realmNum = 2;

    oneof account {
        /**
         * A whole number account number, unique within its realm and shard.
         * <p>
         * For any AccountID fields in the query response, transaction records,
         * transaction receipts, or block stream `accountNum` MUST be used.
         */
        int64 accountNum = 3;

        /**
         * An alias value.<br/>
         * Alias is a value used in some contexts to refer to an account when
         * account number is not available, and may be an alias public key, or
         * an EVM address.
         */
        bytes alias = 4;
    }
}

/**
 * An unique identifier for a topic.<br/>
 * Topics are part of the consensus service, messages are published to a topic.
 */
message TopicID {
    /**
     * A whole number shard identifier.
     */
    int64 shardNum = 1;

    /**
     * A whole number realm identifier.
     */
    int64 realmNum = 2;

    /**
     * A whole number topic identifier, unique within its realm and shard.
     */
    int64 topicNum = 3;
}


/**
 * A transaction identifier.<br/>
 * This is used for retrieving receipts and records for a transaction
 * and internally by the network for detecting when duplicate transactions are
 * submitted.
 *
 * A transaction may be processed more reliably by submitting it to
 * several nodes, each with a different node account, but all with the same
 * TransactionID. Then, the transaction will take effect when the first of all
 * those nodes submits the transaction and it reaches consensus. The other
 * transactions SHALL NOT be executed (and SHALL result in a
 * `DUPLICATE_TRANSACTION` response).<br/>
 * Multiple submission increase reliability on the assumption that an error in,
 * for example, network connectivity will not affect all nodes equally. Latency
 * might be slightly lower, if one node is handling intake significantly slower
 * than others, for example. The base transaction fee is required for each
 * submission, however, so the total fees charged are significantly higher when
 * using this approach.
 *
 * ### Requirements
 * Each transaction identifier MUST be unique.<br/>
 * Multiple transactions MAY be submitted with the same transaction
 * identifier, but all except the first SHALL be rejected as duplicate
 * transactions.<br/>
 * An identifier MUST specify a `payer` account to be charged all fees
 * associated with the transaction.<br/>
 * The `payer` account MUST exist and MUST have sufficient HBAR to pay all
 * transaction fees.<br/>
 * An identifier MUST specify a "valid start time".<br/>
 * The "valid start time" MUST be strictly _earlier_ than the current
 * network consensus time when submitted.<br/>
 * The "valid start time" MUST NOT be more than `transaction.maxValidDuration`
 * seconds before the current network consensus time when submitted.<br/>
 * A client-submitted transaction MUST NOT set the `scheduled` flag.
 *
 * ### Additional Notes
 *
 * Additional items applicable to Scheduled Transactions:
 *
 *  - The ID of a Scheduled Transaction, once executed, SHALL inherit both
 *    `transactionValidStart` and `accountID` from the `ScheduleCreate`
 *    transaction that created the schedule.
 *  - The `scheduled` property SHALL be set for Scheduled Transactions.
 */
message TransactionID {
    /**
     * A timestamp for the transaction start time.<br/>
     * This is the earliest expected start time for this transaction.
     * <p>
     * This value MUST be strictly less than `consensusTimestamp` when the
     * transaction is submitted.
     */
    gradido.Timestamp transactionValidStart = 1;

    /**
     * An Account identifier.
     * <p>
     * The identified account SHALL pay transaction fees for this transaction.
     */
    AccountID accountID = 2;

    /**
     * A scheduled transaction flag.<br/>
     * If set, this transaction represents the execution of a Schedule after
     * all necessary signatures are gathered.
     * <p>
     * This flag MUST NOT be set in a user-submitted transaction.
     */
    bool scheduled = 3;

    /**
     * An identifier for an internal transaction.<br/>
     * An internal transaction is one that was spawned as part of handling a
     * user transaction. These internal transactions share the
     * transactionValidStart and accountID of the user transaction, so a nonce
     * is necessary to give them a unique TransactionID.
     * <p>
     * An example is when a "parent" ContractCreate or ContractCall transaction
     * calls one or more HTS precompiled contracts; each of the "child"
     * transactions spawned for a precompile has a transaction id with a
     * different nonce.
     * <p>
     * This value MUST be unset for user-submitted transactions.
     */
    int32 nonce = 4;
}
